version: '3'
services:
  app:
    build:
      context: .
      dockerfile: images/php/Dockerfile
    container_name: inner-circle-app
    volumes:
      - ./project:/var/www/html
    tty: true
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
